import "./globals.css";
import Navbar from "./component/navbar/Navbar";
import { Roboto } from "next/font/google";
import Footer from "./component/footer/Footer";
import BottomFooter from "./component/footer/BottomFooter";

const roboto = Roboto({
  weight: ['400','500','600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Interior Design Website",
  description: "Generated by Toscroll Technologies",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
        <BottomFooter />
      </body>
    </html>
  );
}
